spring:
  application:
    name: common-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jwt:
    secret: "aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789+AbCdEfG="
    expiration: 86400000
    issuer: "Yegna-Sai-Anand-Akella"
  logging:
    level:
      org.springframework.security: DEBUG

resilience4j.circuitbreaker:
  instances:
    user-service:
      register-health-indicator: true
      failure-rate-threshold: 50
      minimum-number-of-calls: 5
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
user-service:
  url: http://localhost:8081