server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://stadium-rds.c9oi8wkymk82.us-east-2.rds.amazonaws.com/user_service
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: "your-256-bit-secret-key-must-be-32-chars-long"
  expiration: 3600000 # 24 hours
  refresh-expiration: 86400000
  

user-service:
  url: http://localhost:8081
resilience4j:
  timelimiter:
    enabled: false
eureka:
  client:
    enabled: false
flyway:
  enabled: false
  baseline-on-migrate: true
  locations: classpath:db/migration
  schemas: public
  validate-on-migrate: true
logging:
  level:
    org.springframework.security: DEBUG
    org.stadium: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: org.stadium
  paths-to-match: /api/**