server:
  port: 8081
  
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: "your-256-bit-secret-key-must-be-32-chars-long"
  expiration: 86400000  # 24h in milliseconds

