# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stadium.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stadium.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstadium.proto\x12\x07stadium\"#\n\x12\x45ventSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1c\n\x0e\x45ventIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\";\n\x11\x45ventListResponse\x12&\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x16.stadium.EventResponse\"\x99\x01\n\rEventResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x11\n\tdate_time\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x17\n\x0f\x61vailable_seats\x18\x07 \x01(\x05\x12\x0e\n\x06status\x18\x08 \x01(\t2\xa2\x01\n\x13StadiumEventService\x12G\n\x0cSearchEvents\x12\x1b.stadium.EventSearchRequest\x1a\x1a.stadium.EventListResponse\x12\x42\n\x0fGetEventDetails\x12\x17.stadium.EventIdRequest\x1a\x16.stadium.EventResponseB*\n\x18org.stadium.common.protoB\x0cStadiumProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stadium_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.stadium.common.protoB\014StadiumProtoP\001'
  _globals['_EVENTSEARCHREQUEST']._serialized_start=26
  _globals['_EVENTSEARCHREQUEST']._serialized_end=61
  _globals['_EVENTIDREQUEST']._serialized_start=63
  _globals['_EVENTIDREQUEST']._serialized_end=91
  _globals['_EVENTLISTRESPONSE']._serialized_start=93
  _globals['_EVENTLISTRESPONSE']._serialized_end=152
  _globals['_EVENTRESPONSE']._serialized_start=155
  _globals['_EVENTRESPONSE']._serialized_end=308
  _globals['_STADIUMEVENTSERVICE']._serialized_start=311
  _globals['_STADIUMEVENTSERVICE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
