# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stadium_pb2 as stadium__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stadium_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StadiumEventServiceStub(object):
    """The Connection Interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchEvents = channel.unary_unary(
                '/stadium.StadiumEventService/SearchEvents',
                request_serializer=stadium__pb2.EventSearchRequest.SerializeToString,
                response_deserializer=stadium__pb2.EventListResponse.FromString,
                _registered_method=True)
        self.GetEventDetails = channel.unary_unary(
                '/stadium.StadiumEventService/GetEventDetails',
                request_serializer=stadium__pb2.EventIdRequest.SerializeToString,
                response_deserializer=stadium__pb2.EventResponse.FromString,
                _registered_method=True)


class StadiumEventServiceServicer(object):
    """The Connection Interface
    """

    def SearchEvents(self, request, context):
        """Agent: "I need events matching X"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventDetails(self, request, context):
        """Agent: "Get details for ID Y"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StadiumEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEvents,
                    request_deserializer=stadium__pb2.EventSearchRequest.FromString,
                    response_serializer=stadium__pb2.EventListResponse.SerializeToString,
            ),
            'GetEventDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventDetails,
                    request_deserializer=stadium__pb2.EventIdRequest.FromString,
                    response_serializer=stadium__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stadium.StadiumEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stadium.StadiumEventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StadiumEventService(object):
    """The Connection Interface
    """

    @staticmethod
    def SearchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stadium.StadiumEventService/SearchEvents',
            stadium__pb2.EventSearchRequest.SerializeToString,
            stadium__pb2.EventListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stadium.StadiumEventService/GetEventDetails',
            stadium__pb2.EventIdRequest.SerializeToString,
            stadium__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
